services:
  backend:
    container_name: geno-tree-server
    build:
      context: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: geno-tree-db
    image: postgres:17.5
    restart: always
    user: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=geno-tree-db
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
volumes:
  db-data:
